name: Flaky Test Detector

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository to analyze (e.g., <org-name>/platform-engineer-tech-case-49378219)'
        required: true
        type: string
      workflow-name:
        description: 'Name of the workflow to analyze (e.g., CI)'
        required: true
        type: string
      runs-limit:
        description: 'Number of previous runs to analyze'
        default: 10
        type: number
      branch:
        description: 'Branch to filter runs (e.g., main)'
        default: 'main'
        type: string
    secrets:
      github-token:
        description: 'GitHub PAT with repo and workflow scopes'
        required: true
    outputs:
      flaky-tests:
        description: 'JSON string of flaky tests and their failure counts'
        value: ${{ jobs.detect-flaky-tests.outputs.flaky-tests }}

jobs:
  detect-flaky-tests:
    runs-on: ubuntu-latest
    outputs:
      flaky-tests: ${{ steps.process-results.outputs.flaky-tests }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch previous workflow runs
        id: fetch-runs
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          REPO: ${{ inputs.repository }}
          WORKFLOW_NAME: ${{ inputs.workflow-name }}
          RUNS_LIMIT: ${{ inputs.runs-limit }}
          BRANCH: ${{ inputs.branch }}
        run: |
          python - <<EOF
          import requests
          import json

          headers = {"Authorization": f"Bearer $GITHUB_TOKEN", "Accept": "application/vnd.github.v3+json"}
          url = f"https://api.github.com/repos/$REPO/actions/runs?per_page=$RUNS_LIMIT&branch=$BRANCH"
          response = requests.get(url, headers=headers)
          response.raise_for_status()
          runs = response.json()["workflow_runs"]
          runs = [run for run in runs if run["name"] == "$WORKFLOW_NAME"]
          run_ids = [run["id"] for run in runs]
          print(f"Found {len(run_ids)} runs for workflow '$WORKFLOW_NAME'")
          with open("run_ids.txt", "w") as f:
              json.dump(run_ids, f)
          EOF

      - name: Fetch and parse test artifacts
        id: process-results
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          REPO: ${{ inputs.repository }}
        run: |
          python - <<EOF
          import requests
          import json
          import xml.etree.ElementTree as ET
          import zipfile
          import os

          headers = {"Authorization": f"Bearer $GITHUB_TOKEN", "Accept": "application/vnd.github.v3+json"}
          with open("run_ids.txt") as f:
              run_ids = json.load(f)

          test_results = {}
          for run_id in run_ids:
              url = f"https://api.github.com/repos/$REPO/actions/runs/{run_id}/artifacts"
              response = requests.get(url, headers=headers)
              response.raise_for_status()
              artifacts = response.json()["artifacts"]
              for artifact in artifacts:
                  if artifact["name"] == "test-reports":
                      zip_url = artifact["archive_download_url"]
                      zip_response = requests.get(zip_url, headers=headers)
                      zip_response.raise_for_status()
                      with open("artifacts.zip", "wb") as f:
                          f.write(zip_response.content)
                      with zipfile.ZipFile("artifacts.zip", "r") as zip_ref:
                          zip_ref.extractall("artifacts")
                      for file in os.listdir("artifacts"):
                          if file.endswith(".xml"):
                              tree = ET.parse(f"artifacts/{file}")
                              root = tree.getroot()
                              for testcase in root.findall(".//testcase"):
                                  name = testcase.get("name")
                                  if testcase.find("failure") is not None:
                                      test_results.setdefault(name, {"pass": 0, "fail": 0})["fail"] += 1
                                  else:
                                      test_results.setdefault(name, {"pass": 0, "fail": 0})["pass"] += 1

          flaky_tests = {k: v["fail"] for k, v in test_results.items() if v["pass"] > 0 and v["fail"] > 0}
          with open("flaky-tests.json", "w") as f:
              json.dump(flaky_tests, f)
          print(f"Flaky tests: {json.dumps(flaky_tests)}")
          print(f"flaky-tests={json.dumps(flaky_tests)}", file=open("$GITHUB_OUTPUT", "a"))
          EOF

      - name: Summarize results
        run: |
          echo "Flaky Test Summary:"
          jq -r 'to_entries | .[] | "- \(.key): failed \(.value) out of ${{ inputs.runs-limit }} runs"' flaky-tests.json > flaky-tests-summary.txt
          cat flaky-tests-summary.txt
        env:
          FLAKY_TESTS: ${{ steps.process-results.outputs.flaky-tests }}

      - name: Upload flaky test summary
        uses: actions/upload-artifact@v4
        with:
          name: flaky-tests-summary
          path: flaky-tests-summary.txt





